---------------------------
-- BCP --
---------------------------
CREATE INDEX SPFB_BCP_USERS_MD_IX3 ON SPFB_BCP_USERS_MD (COMPANY_CODE ASC); 

CREATE INDEX SPFB_BCP_ADMINISTRATOR_AUDIT_MD_IX2 ON SPFB_BCP_ADMINISTRATOR_AUDIT_MD (USER_NAME ASC);
CREATE INDEX SPFB_BCP_ADMINISTRATOR_AUDIT_MD_IX3 ON SPFB_BCP_ADMINISTRATOR_AUDIT_MD (OPERATION_DATE ASC);

CREATE INDEX SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD_IX2 ON SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD (PRODUCT_CODE ASC);
CREATE INDEX SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD_IX3 ON SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD (COMPANY_CODE ASC);

CREATE INDEX SPFB_SP2_FILE_MD_IX2 ON SPFB_SP2_FILE_SYS_MD (QUEUE_NAME ASC);
CREATE INDEX SPFB_SP2_FILE_MD_IX3 ON SPFB_SP2_FILE_SYS_MD (INTERNAL_NUMBER ASC);
CREATE INDEX SPFB_SP2_FILE_MD_IX4 ON SPFB_SP2_FILE_SYS_MD (SENDER ASC);
CREATE INDEX SPFB_SP2_FILE_MD_IX5 ON SPFB_SP2_FILE_SYS_MD (ORIGINAL_FILENAME ASC);
CREATE INDEX SPFB_SP2_FILE_MD_IX6 ON SPFB_SP2_FILE_SYS_MD (ARRIVAL_DATE ASC);
