---------------------------
-- BCP --
---------------------------
CREATE TABLE SPFB_BCP_USERS_MD (
      ID_ROW BIGINT NOT NULL,
      ID_FILESET BIGINT NOT NULL,
      ID_FILE BIGINT,
      USER_NAME VARCHAR(10),
      FIRST_NAME VARCHAR(50),
      LAST_NAME VARCHAR(50),
      COMPANY_CODE VARCHAR(10),
      USER_EMAIL VARCHAR(128),
      USER_FUNCTION VARCHAR(256),
      LOGON_TRIES INTEGER,
      USER_TYPE VARCHAR(1),
      STATUS VARCHAR(1),
      CREATE_DATE TIMESTAMP,
      UPDATE_DATE TIMESTAMP,
      GENERATE_MAIL SMALLINT,
      GENERATE_REPORT SMALLINT
)  IN "FB_TS_METADATA";
      
ALTER TABLE SPFB_BCP_USERS_MD ADD CONSTRAINT SPFB_BCP_USERS_MD_PK PRIMARY KEY (ID_ROW);
ALTER TABLE SPFB_BCP_USERS_MD ADD CONSTRAINT SPFB_BCP_USERS_MD_FK1 FOREIGN KEY (ID_FILESET) REFERENCES SPFB_FILESET (ID_FILESET) ON DELETE CASCADE;
CREATE INDEX SPFB_BCP_USERS_MD_IX1 ON SPFB_BCP_USERS_MD (ID_FILESET, ID_FILE ASC); 
CREATE INDEX SPFB_BCP_USERS_MD_IX2 ON SPFB_BCP_USERS_MD (USER_NAME ASC); 
CREATE SEQUENCE SPFB_BCP_USERS_MD_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE TABLE SPFB_BCP_COMPANY_MD (
      ID_ROW BIGINT NOT NULL,
      ID_FILESET BIGINT NOT NULL,
      ID_FILE BIGINT,
      COMPANY_CODE VARCHAR(10),
      COMPANY_NAME VARCHAR(128),
      DESCRIPTION VARCHAR(512),
      COMPANY_ADDRESS VARCHAR(512),
      COUNTRY VARCHAR(128),
      OFFICE_HOURS VARCHAR(256),
      TELEPHONE VARCHAR(50),
      FAX VARCHAR(50),
      RESPONSIBLE VARCHAR(128),
      RESPONSIBLE_EMAIL VARCHAR(128),
      TECHNICAL_RESPONSIBLE VARCHAR(128),
      TECHNICAL_RESPONSIBLE_EMAIL VARCHAR(128),
      DOC_TYPE	VARCHAR(10),
      DOC_VALUE VARCHAR(50),
      PROVINCE	VARCHAR(50),
      DISTRICT VARCHAR(50),
      DEPARTMENT VARCHAR(50),
      OUT_QUEUE_NAME VARCHAR(50),
      IN_QUEUE_NAME VARCHAR(50),
      LAST_INSTALL_DATE TIMESTAMP,
      AFFILIATION_DATE TIMESTAMP,
      DISAFFILIATION_DATE TIMESTAMP,
      CLIENT_TYPE VARCHAR(1),
      USE_FREQUENCY VARCHAR(128),
      AVERAGE_SENT_VOL VARCHAR(50),
      STATUS VARCHAR(1),
      CREATE_DATE TIMESTAMP,
      UPDATE_DATE TIMESTAMP,
      CONTINGENCY SMALLINT,
     ACTIVATION_DATE TIMESTAMP
)  IN "FB_TS_METADATA";
      
ALTER TABLE SPFB_BCP_COMPANY_MD ADD CONSTRAINT SPFB_BCP_COMPANY_MD_PK PRIMARY KEY (ID_ROW);
ALTER TABLE SPFB_BCP_COMPANY_MD ADD CONSTRAINT SPFB_BCP_COMPANY_MD_FK1 FOREIGN KEY (ID_FILESET) REFERENCES SPFB_FILESET (ID_FILESET) ON DELETE CASCADE;
CREATE INDEX SPFB_BCP_COMPANY_MD_IX1 ON SPFB_BCP_COMPANY_MD (ID_FILESET, ID_FILE ASC); 
CREATE INDEX SPFB_BCP_COMPANY_MD_IX2 ON SPFB_BCP_COMPANY_MD (COMPANY_CODE ASC); 
CREATE SEQUENCE SPFB_BCP_COMPANY_MD_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE TABLE SPFB_BCP_PRODUCTS_MD (
      ID_ROW BIGINT NOT NULL,
      ID_FILESET BIGINT NOT NULL,
      ID_FILE BIGINT,
      PRODUCT_CODE VARCHAR(4),
      DESCRIPTION VARCHAR(50),
      DISPLACEMENT INTEGER,
      MONDAY_START TIMESTAMP,
      MONDAY_END TIMESTAMP,
      TUESDAY_START TIMESTAMP,
      TUESDAY_END TIMESTAMP,
      WEDNESDAY_START TIMESTAMP,
      WEDNESDAY_END TIMESTAMP,
      THURSDAY_START TIMESTAMP,
      THURSDAY_END TIMESTAMP,
      FRIDAY_START TIMESTAMP,
      FRIDAY_END TIMESTAMP,
      SATURDAY_START TIMESTAMP,
      SATURDAY_END TIMESTAMP,
      SUNDAY_START TIMESTAMP,
      SUNDAY_END TIMESTAMP,
      VALIDATOR SMALLINT,
      CONSOLIDATION_STATE VARCHAR(1),
      DISTRIBUTOR_STATE VARCHAR(1),
      APP_INTERFACE_TYPE VARCHAR(1),
      APP_QUEUE_IN VARCHAR(255),
      APP_FILE_PATH_IN VARCHAR(255),
      APP_FILE_PATH_OUT VARCHAR(255),
      OUT_QUEUE_NAME VARCHAR(50),
      IN_QUEUE_NAME VARCHAR(50),
      CREATE_DATE TIMESTAMP,
      UPDATE_DATE TIMESTAMP
)  IN "FB_TS_METADATA";

ALTER TABLE SPFB_BCP_PRODUCTS_MD ADD CONSTRAINT SPFB_BCP_PRODUCTS_MD_PK PRIMARY KEY (ID_ROW);
ALTER TABLE SPFB_BCP_PRODUCTS_MD ADD CONSTRAINT SPFB_BCP_PRODUCTS_MD_FK1 FOREIGN KEY (ID_FILESET) REFERENCES SPFB_FILESET (ID_FILESET) ON DELETE CASCADE;
CREATE INDEX SPFB_BCP_PRODUCTS_MD_IX1 ON SPFB_BCP_PRODUCTS_MD (ID_FILESET, ID_FILE ASC);
CREATE INDEX SPFB_BCP_PRODUCTS_MD_IX2 ON SPFB_BCP_PRODUCTS_MD (PRODUCT_CODE ASC);
CREATE SEQUENCE FB_BCP_PRODUCTS_MD_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE TABLE SPFB_BCP_COMPANY_PRODUCT_MD (
      ID_ROW BIGINT NOT NULL,
      ID_FILESET BIGINT NOT NULL,
      ID_FILE BIGINT,
      COMPANY_CODE VARCHAR(10),
      PRODUCT_CODE VARCHAR(4),
      USU_PROD_CODE VARCHAR(5),
      CREATE_DATE TIMESTAMP
)  IN "FB_TS_METADATA";

ALTER TABLE SPFB_BCP_COMPANY_PRODUCT_MD ADD CONSTRAINT SPFB_BCP_COMPANY_PRODUCT_MD_PK PRIMARY KEY (ID_ROW);
ALTER TABLE SPFB_BCP_COMPANY_PRODUCT_MD ADD CONSTRAINT SPFB_BCP_COMPANY_PRODUCT_MD_FK1 FOREIGN KEY (ID_FILESET) REFERENCES SPFB_FILESET (ID_FILESET) ON DELETE CASCADE;
CREATE INDEX SPFB_BCP_COMPANY_PRODUCT_MD_IX1 ON SPFB_BCP_COMPANY_PRODUCT_MD (ID_FILESET, ID_FILE ASC);
CREATE INDEX SPFB_BCP_COMPANY_PRODUCT_MD_IX2 ON SPFB_BCP_COMPANY_PRODUCT_MD (COMPANY_CODE ASC);
CREATE INDEX SPFB_BCP_COMPANY_PRODUCT_MD_IX3 ON SPFB_BCP_COMPANY_PRODUCT_MD (PRODUCT_CODE ASC);
CREATE SEQUENCE FB_BCP_COMPANY_PRODUCT_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE TABLE SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD (
      ID_ROW BIGINT NOT NULL,
      ID_FILESET BIGINT NOT NULL,
      ID_FILE BIGINT,
      PRODUCT_CODE VARCHAR(4) ,
      FILE_STATUS VARCHAR(1),
      VALIDATOR_RECORD_COUNT INTEGER,
      COMPANY_CODE VARCHAR(10)
)  IN "FB_TS_METADATA";

ALTER TABLE SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD ADD CONSTRAINT SPFB_BCP_SP2_FILE_SYS_RODUCTS_MD_PK PRIMARY KEY (ID_ROW);
ALTER TABLE SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD ADD CONSTRAINT SPFB_BCP_SP2_FILE_SYS_RODUCTS_MD_FK1 FOREIGN KEY (ID_FILESET) REFERENCES SPFB_FILESET (ID_FILESET) ON DELETE CASCADE;
CREATE INDEX SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD_IX1 ON SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD (ID_FILESET, ID_FILE ASC);
CREATE SEQUENCE FBSP2_FILE_SYS_PRODUCTS_MD_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE TABLE SPFB_BCP_ADMINISTRATOR_AUDIT_MD (
      ID_ROW BIGINT NOT NULL,
      ID_FILESET BIGINT NOT NULL,
      ID_FILE BIGINT,
      OPERATION_CODE VARCHAR(4),
      OPERATION_DESC VARCHAR(50) ,
      OPERATION_RESULT SMALLINT ,
      USER_NAME VARCHAR(25) ,
      USER_FULL_NAME VARCHAR(60) ,
      DESCRIPTION VARCHAR(100) ,
      OPERATION_DATE TIMESTAMP
)  IN "FB_TS_METADATA";

ALTER TABLE SPFB_BCP_ADMINISTRATOR_AUDIT_MD ADD CONSTRAINT SPFB_BCP_ADMINISTRATOR_AUDIT_MD_PK PRIMARY KEY (ID_ROW);
ALTER TABLE SPFB_BCP_ADMINISTRATOR_AUDIT_MD ADD CONSTRAINT SPFB_BCP_ADMINISTRATOR_AUDIT_MD_FK1 FOREIGN KEY (ID_FILESET) REFERENCES SPFB_FILESET (ID_FILESET) ON DELETE CASCADE;
CREATE INDEX SPFB_BCP_ADMINISTRATOR_AUDIT_MD_IX1 ON SPFB_BCP_ADMINISTRATOR_AUDIT_MD (ID_FILESET, ID_FILE ASC);
CREATE SEQUENCE FB_BCP_ADMINISTRATOR_AUDIT_MD_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE TABLE SPFB_BCP_SYSTEM_PROPERTIES_MD (
      ID_ROW BIGINT NOT NULL,
      ID_FILESET BIGINT NOT NULL,
      ID_FILE BIGINT,
      PARAMETER VARCHAR(100),
      VALUE VARCHAR(255),
      DESCRIPTION VARCHAR(512),
      APPLICATION VARCHAR(1),
      STATUS VARCHAR(1),
      CREATE_DATE TIMESTAMP,
      UPDATE_DATE TIMESTAMP
)  IN "FB_TS_METADATA";

ALTER TABLE SPFB_BCP_SYSTEM_PROPERTIES_MD ADD CONSTRAINT SPFB_BCP_SYSTEM_PROPERTIES_MD_PK PRIMARY KEY (ID_ROW);
ALTER TABLE SPFB_BCP_SYSTEM_PROPERTIES_MD ADD CONSTRAINT SPFB_BCP_SYSTEM_PROPERTIES_MD_FK1 FOREIGN KEY (ID_FILESET) REFERENCES SPFB_FILESET (ID_FILESET) ON DELETE CASCADE;
CREATE INDEX SPFB_BCP_SYSTEM_PROPERTIES_MD_IX1 ON SPFB_BCP_SYSTEM_PROPERTIES_MD (ID_FILESET, ID_FILE ASC);
CREATE SEQUENCE FB_BCP_SYSTEM_PROPERTIES_MD_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE CACHE 20;

CREATE VIEW SPFB_BCP_SP2_FILE_SYS_MD (
	"ID_FILESET",
	"NODE_NAME",
	"QUEUE_MANAGER_NAME",
	"QUEUE_NAME",
	"ADDRESS_TYPE",
	"INTERNAL_NUMBER",
	"MESSAGE_FILE_ID",
	"CORRELATION_ID",
	"SENDER",
	"USER_CLASS",
	"DESTINATION_FILENAME",
	"DESCRIPTION",
	"START_PUT_DATE",
	"EXPIRY_DATE",
	"DESTINATION_PATHNAME",
	"ORIGINAL_FILENAME",
	"CODEPAGE",
	"EOR_EOF",
	"PRIORITY",
	"FILE_LENGTH",
	"USER_ID",
	"SESSION_ID",
	"FIRST_READ_DATE",
	"LAST_READ_DATE",
	"ARRIVAL_DATE",
	"BINARY_FILE",
	"Z_COMPRESS",
	"DSTK",
	"LOCALLY_EXTERNAL",
	"DESTINATION_EXTERNAL",
	"ORIGIN_QUEUE_MANAGER",
	"ORIGIN_QUEUE",
	"PRODUCT_CODE",
	"FILE_URL",
	"FILE_STATUS", 
    "VALIDATOR_RECORD_COUNT",
    "COMPANY_CODE"
) 
AS SELECT
	a.ID_FILESET "ID_FILESET",
	a.NODE_NAME "NODE_NAME",
	a.QUEUE_MANAGER_NAME "QUEUE_MANAGER_NAME",
	a.QUEUE_NAME "QUEUE_NAME",
	a.ADDRESS_TYPE "ADDRESS_TYPE",
	a.INTERNAL_NUMBER "INTERNAL_NUMBER",
	a.MESSAGE_FILE_ID "MESSAGE_FILE_ID",
	a.CORRELATION_ID "CORRELATION_ID",
	a.SENDER "SENDER",
	a.USER_CLASS "USER_CLASS",
	a.DESTINATION_FILENAME "DESTINATION_FILENAME",
	a.DESCRIPTION "DESCRIPTION",
	a.START_PUT_DATE "START_PUT_DATE",
	a.EXPIRY_DATE "EXPIRY_DATE",
	a.DESTINATION_PATHNAME "DESTINATION_PATHNAME",
	a.ORIGINAL_FILENAME "ORIGINAL_FILENAME",
	a.CODEPAGE "CODEPAGE",
	a.EOR_EOF "EOR_EOF",
	a.PRIORITY "PRIORITY",
	a.FILE_LENGTH "FILE_LENGTH",
	a.USER_ID "USER_ID",
	a.SESSION_ID "SESSION_ID",
	a.FIRST_READ_DATE "FIRST_READ_DATE",
	a.LAST_READ_DATE "LAST_READ_DATE",
	a.ARRIVAL_DATE "ARRIVAL_DATE",
	a.BINARY_FILE "BINARY_FILE",
	a.Z_COMPRESS "Z_COMPRESS",
	a.DSTK "DSTK",
	a.LOCALLY_EXTERNAL "LOCALLY_EXTERNAL",
	a.DESTINATION_EXTERNAL "DESTINATION_EXTERNAL",
	a.ORIGIN_QUEUE_MANAGER "ORIGIN_QUEUE_MANAGER",
	a.ORIGIN_QUEUE "ORIGIN_QUEUE",
	b.PRODUCT_CODE "PRODUCT_CODE",
	c.FILE_URL "FILE_URL",
	b.FILE_STATUS "FILE_STATUS", 
    b.VALIDATOR_RECORD_COUNT "VALIDATOR_RECORD_COUNT",
    b.COMPANY_CODE "COMPANY_CODE"

FROM SPFB_SP2_FILE_SYS_MD a LEFT JOIN SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD b ON a.ID_FILESET = b.ID_FILESET LEFT JOIN SPFB_FILES_SYS_MD c ON a.ID_FILESET = c.ID_FILESET;

COMMIT;

----------------------------------------------------------------------------
-- STORED PROCEDURES --
----------------------------------------------------------------------------

-- DROP PROCEDURE INCREMENT_COUNTER (INTEGER, BIGINT);

CREATE PROCEDURE INCREMENT_COUNTER ( IN counterID INTEGER, OUT nextVal BIGINT )
DYNAMIC RESULT SETS 1
------------------------------------------------------------------------
-- SQL Stored Procedure 
------------------------------------------------------------------------
BEGIN
	SELECT LAST_VALUE INTO nextVal FROM SPMFTS_COUNTERS WHERE ID_COUNTER = counterID;
		
	SET nextVal = nextVal + 1;
	
	UPDATE SPMFTS_COUNTERS SET LAST_VALUE = nextVal  WHERE ID_COUNTER = counterID;
END;
/

-- DROP PROCEDURE INSERT_CLASS_IN_DICT (BIGINT, VARCHAR(32), INTEGER, VARCHAR(256), VARCHAR(256));

CREATE PROCEDURE INSERT_CLASS_IN_DICT ( IN classId BIGINT, IN className VARCHAR(256), IN classType INTEGER, IN java_class VARCHAR(256), IN desc VARCHAR(256))
DYNAMIC RESULT SETS 1
------------------------------------------------------------------------
-- SQL Stored Procedure 
------------------------------------------------------------------------
BEGIN
	INSERT INTO SPFB_META_CLASS(ID_METADATA_CLASS, CLASS_NAME, CLASS_TYPE, JAVA_CLASS, DESCRIPTION) VALUES (classId, className, classType, java_class, desc);	
END;
/

-- DROP PROCEDURE INSERT_METADATA_IN_DICT (BIGINT, INTEGER, VARCHAR(32), VARCHAR(128), INTEGER, INTEGER);

CREATE PROCEDURE INSERT_METADATA_IN_DICT ( IN classId BIGINT,
					   IN typeId INTEGER,
					   IN metadtaName VARCHAR(32), 
					   IN desc VARCHAR(128),
					   IN length INTEGER,
					   IN prec INTEGER 
					   )
DYNAMIC RESULT SETS 1
------------------------------------------------------------------------
-- SQL Stored Procedure 
------------------------------------------------------------------------
BEGIN
	DECLARE metadataId BIGINT;
	
	CALL INCREMENT_COUNTER(7, metadataId);
	
	INSERT INTO SPFB_METADATA(ID_METADATA, ID_METADATA_TYPE, METADATA_DESCRIPTION, METADATA_NAME, LENGTH, PRECISION) VALUES (metadataId, typeId, desc, metadtaName, length, prec);
	INSERT INTO SPFB_META_CLASS_STRUCT (ID_METADATA_CLASS, ID_METADATA, METADATA_ORDER) VALUES(classId, metadataId, 100); 
END;
/


CREATE PROCEDURE UPDATE_METADATA_DICT
------------------------------------------------------------------------
-- SQL Stored Procedure 
------------------------------------------------------------------------
BEGIN
	DECLARE classId BIGINT;
	
------------------------------------------------------------------------
-- Protected Metadata Class SPFB_BCP_USERS_MD
------------------------------------------------------------------------
	CALL INCREMENT_COUNTER(6, classId);
	CALL INSERT_CLASS_IN_DICT(classId, 'SPFB_BCP_USERS_MD', 0, '', 'Users Metadata for BCP');

	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USER_NAME', 'USER_NAME', 10, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'FIRST_NAME', 'FIRST_NAME', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'LAST_NAME', 'LAST_NAME', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'COMPANY_CODE', 'COMPANY_CODE', 10, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USER_EMAIL', 'USER_EMAIL', 128, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USER_FUNCTION', 'USER_FUNCTION', 256, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'LOGON_TRIES', 'LOGON_TRIES', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'STATUS', 'STATUS', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USER_TYPE', 'USER_TYPE', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'CREATE_DATE', 'CREATE_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'UPDATE_DATE', 'UPDATE_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'GENERATE_MAIL', 'GENERATE_MAIL', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'GENERATE_REPORT', 'GENERATE_REPORT', 0, 0);
	
------------------------------------------------------------------------
-- Protected Metadata Class SPFB_BCP_COMPANY_MD
------------------------------------------------------------------------
	CALL INCREMENT_COUNTER(6, classId);
	CALL INSERT_CLASS_IN_DICT(classId, 'SPFB_BCP_COMPANY_MD', 0, '', 'Company Metadata for BCP');
	
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'COMPANY_CODE', 'COMPANY_CODE', 10, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'COMPANY_NAME', 'COMPANY_NAME', 128, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DESCRIPTION', 'DESCRIPTION', 256, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'COMPANY_ADDRESS', 'COMPANY_ADDRESS', 256, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'COUNTRY', 'COUNTRY', 256, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'OFFICE_HOURS', 'OFFICE_HOURS', 256, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'TELEPHONE', 'TELEPHONE', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'FAX', 'FAX', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'RESPONSIBLE', 'TRESPONSIBLE', 128, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'RESPONSIBLE_EMAIL', 'TRESPONSIBLE_EMAIL', 128, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'TECHNICAL_RESPONSIBLE', 'TECHNICAL_RESPONSIBLE', 128, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'TECHNICAL_RESPONSIBLE_EMAIL', 'TECHNICAL_RESPONSIBLE_EMAIL', 128, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DOC_TYPE', 'DOC_TYPE', 10, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DOC_VALUE', 'DOC_VALUE', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'PROVINCE', 'PROVINCE', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DISTRICT', 'DISTRICT', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DEPARTMENT', 'DEPARTMENT', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'OUT_QUEUE_NAME', 'OUT_QUEUE_NAME', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'IN_QUEUE_NAME', 'IN_QUEUE_NAME', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'LAST_INSTALL_DATE', 'LAST_INSTALL_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'AFFILIATION_DATE', 'AFFILIATION_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'DISAFFILIATION_DATE', 'DISAFFILIATION_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'CLIENT_TYPE', 'CLIENT_TYPE', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USE_FREQUENCY', 'USE_FREQUENCY', 128, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'AVERAGE_SENT_VOL', 'AVERAGE_SENT_VOL', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'STATUS', 'STATUS', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'CREATE_DATE', 'CREATE_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'UPDATE_DATE', 'UPDATE_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'CONTINGENCY', 'CONTINGENCY', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'ACTIVATION_DATE', 'ACTIVATION_DATE', 0, 0);
	
------------------------------------------------------------------------
-- Protected Metadata Class SPFB_BCP_PRODUCTS_MD
------------------------------------------------------------------------
	CALL INCREMENT_COUNTER(6, classId);
	CALL INSERT_CLASS_IN_DICT(classId, 'SPFB_BCP_PRODUCTS_MD', 0, '', 'Products Metadata for BCP');
	
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'PRODUCT_CODE', 'PRODUCT_CODE', 4, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DESCRIPTION', 'DESCRIPTION', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'DISPLACEMENT', 'DISPLACEMENT', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'MONDAY_START', 'MONDAY_START', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'MONDAY_END', 'MONDAY_END', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'TUESDAY_START', 'TUESDAY_START', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'TUESDAY_END', 'TUESDAY_END', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'WEDNESDAY_START', 'WEDNESDAY_START', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'WEDNESDAY_END', 'WEDNESDAY_END', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'THURSDAY_START', 'THURSDAY_START', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'THURSDAY_END', 'THURSDAY_END', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'FRIDAY_START', 'FRIDAY_START', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'FRIDAY_END', 'FRIDAY_END', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'SATURDAY_START', 'SATURDAY_START', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'SATURDAY_END', 'SATURDAY_END', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'SUNDAY_START', 'SUNDAY_START', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10, 'SUNDAY_END', 'SUNDAY_END', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2 , 'VALIDATOR', 'VALIDATOR', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'CONSOLIDATION_STATE', 'CONSOLIDATION_STATE', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DISTRIBUTOR_STATE', 'DISTRIBUTOR_STATE', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'APP_INTERFACE_TYPE', 'APP_INTERFACE_TYPE', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'APP_QUEUE_IN', 'APP_QUEUE_IN', 255, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'APP_FILE_PATH_IN', 'APP_FILE_PATH_IN', 255, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'APP_FILE_PATH_OUT', 'APP_FILE_PATH_OUT', 255, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'OUT_QUEUE_NAME', 'OUT_QUEUE_NAME', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'IN_QUEUE_NAME', 'IN_QUEUE_NAME', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'CREATE_DATE', 'CREATE_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'UPDATE_DATE', 'UPDATE_DATE', 0, 0);
	
------------------------------------------------------------------------
-- Protected Metadata Class SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD
------------------------------------------------------------------------
	CALL INCREMENT_COUNTER(6, classId);
	CALL INSERT_CLASS_IN_DICT(classId, 'SPFB_BCP_SP2_FILE_SYS_PRODUCTS_MD', 0, '', 'Filebox Spazio 2 Products Metadata for BCP');

	CALL INSERT_METADATA_IN_DICT(classId, 1, 'PRODUCT_CODE', 'PRODUCT_CODE', 4, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'FILE_STATUS', 'FILE_STATUS', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2 ,'VALIDATOR_RECORD_COUNT', 'VALIDATOR_RECORD_COUNT', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'COMPANY_CODE', 'COMPANY_CODE', 10, 0);
	
------------------------------------------------------------------------
-- Protected Metadata Class SPFB_BCP_COMPANY_PRODUCT_MD
------------------------------------------------------------------------
	CALL INCREMENT_COUNTER(6, classId);
	CALL INSERT_CLASS_IN_DICT(classId, 'SPFB_BCP_COMPANY_PRODUCT_MD', 0, '', 'Company Products Metadata for BCP');

	CALL INSERT_METADATA_IN_DICT(classId, 1, 'COMPANY_CODE', 'COMPANY_CODE', 10, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'PRODUCT_CODE', 'PRODUCT_CODE', 4, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USU_PROD_CODE', 'USU_PROD_CODE', 5, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'CREATE_DATE', 'CREATE_DATE', 0, 0);
	
------------------------------------------------------------------------
-- Protected Metadata Class SPFB_BCP_ADMINISTRATOR_AUDIT_MD
------------------------------------------------------------------------
	CALL INCREMENT_COUNTER(6, classId);
	CALL INSERT_CLASS_IN_DICT(classId, 'SPFB_BCP_ADMINISTRATOR_AUDIT_MD', 0, '', 'Audit Metadata for BCP');

	CALL INSERT_METADATA_IN_DICT(classId, 1, 'OPERATION_CODE', 'OPERATION_CODE', 4, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'OPERATION_DESC', 'OPERATION_DESC', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'OPERATION_RESULT', 'OPERATION_RESULT', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USER_NAME', 'USER_NAME', 25, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USER_FULL_NAME', 'USER_FULL_NAME', 60, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DESCRIPTION', 'DESCRIPTION', 100, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'OPERATION_DATE', 'OPERATION_DATE', 0, 0);

------------------------------------------------------------------------
-- Protected Metadata Class SPFB_BCP_SYSTEM_PROPERTIES_MD
------------------------------------------------------------------------
	CALL INCREMENT_COUNTER(6, classId);
	CALL INSERT_CLASS_IN_DICT(classId, 'SPFB_BCP_SYSTEM_PROPERTIES_MD', 0, '', 'System Properties Metadata for BCP');

	CALL INSERT_METADATA_IN_DICT(classId, 1, 'PARAMETER', 'PARAMETER', 100, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'VALUE', 'VALUE', 255, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DESCRIPTION', 'DESCRIPTION', 512, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'APPLICATION', 'APPLICATION', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'STATUS', 'STATUS', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'CREATE_DATE', 'CREATE_DATE', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 10,'UPDATE_DATE', 'UPDATE_DATE', 0, 0);

	------------------------------------------------------------------------
-- View Metadata Class SPFB_BCP_SP2_FILE_SYS_MD
------------------------------------------------------------------------
	CALL INCREMENT_COUNTER(6, classId);
	CALL INSERT_CLASS_IN_DICT(classId, 'SPFB_BCP_SP2_FILE_SYS_MD', 3, '', 'Filebox Spazio 2 Files System Metadata for BCP');
	
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'NODE_NAME', 'Spazio 2 File NodeName', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'QUEUE_MANAGER_NAME', 'Spazio 2 File QueueManagerName', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'QUEUE_NAME', 'Spazio 2 File QueueName', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'ADDRESS_TYPE', 'Spazio 2 File AddressType', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'INTERNAL_NUMBER', 'Spazio 2 File Internal Number', 18, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'MESSAGE_FILE_ID', 'Spazio 2 Message File Id', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'CORRELATION_ID', 'Spazio 2 File Correlation Id', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'SENDER', 'Spazio 2 File Sender', 10, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USER_CLASS', 'Spazio 2 File User Class', 6, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DESTINATION_FILENAME', 'Spazio 2 File Destination FileName', 258, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DESCRIPTION', 'Spazio 2 File Description', 66, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 6, 'START_PUT_DATE', 'File Start Put Date',  0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 6, 'EXPIRY_DATE', 'File Expiry Date',  0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'DESTINATION_PATHNAME', 'Spazio 2 File Destination Path Name (4200-500-2010)', 258, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'ORIGINAL_FILENAME', 'Spazio 2 File Original File Name (4100-500-2010)', 258, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'CODEPAGE', 'Spazio 2 File CodePAge', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'EOR_EOF', 'Spazio 2 File Eor and Eof', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'PRIORITY', 'Spazio 2 File Priority', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 7, 'FILE_LENGTH', 'Spazio 2 File FileLen', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'USER_ID', 'Spazio 2 File UserId', 18, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'SESSION_ID', 'Spazio 2 File SESSION_ID', 10, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 6, 'FIRST_READ_DATE', 'File First Read Date',  0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 6, 'LAST_READ_DATE', 'File Last Read Date',  0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 6, 'ARRIVAL_DATE', 'File Arrival Date',  0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'BINARY_FILE', 'Spazio 2 File Binary', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'Z_COMPRESS', 'Spazio 2 File Zlib Compression', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'DSTK', 'Spazio 2 File DSTK', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'LOCALLY_EXTERNAL', 'Spazio 2 File Locally External', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'DESTINATION_EXTERNAL', 'Spazio 2 File Destination External', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'ORIGIN_QUEUE_MANAGER', 'Spazio 2 File Original Queue Manager', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'ORIGIN_QUEUE', 'Spazio 2 File Original Queue', 50, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'PRODUCT_CODE', 'BCP Product Code', 4, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'FILE_URL', 'Original File URL',  512, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'FILE_STATUS', 'FILE_STATUS', 1, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 2, 'VALIDATOR_RECORD_COUNT', 'VALIDATOR_RECORD_COUNT', 0, 0);
	CALL INSERT_METADATA_IN_DICT(classId, 1, 'COMPANY_CODE', 'COMPANY_CODE', 10, 0);

END;
/

CALL UPDATE_METADATA_DICT;
COMMIT;
	

DROP PROCEDURE INCREMENT_COUNTER (INTEGER, BIGINT);
DROP PROCEDURE INSERT_CLASS_IN_DICT (BIGINT, VARCHAR(256), INTEGER, VARCHAR(256), VARCHAR(256));
DROP PROCEDURE INSERT_METADATA_IN_DICT (BIGINT, INTEGER, VARCHAR(32), VARCHAR(128), INTEGER, INTEGER);
DROP PROCEDURE UPDATE_METADATA_DICT;

COMMIT;
