select TBSPACE from syscat.tablespaces where TBSPACE like 'FB%';
CREATE TEMPORARY TABLESPACE "FB_TS_TEMPUSR01" IN DATABASE PARTITION GROUP IBMTEMPGROUP PAGESIZE 16384 MANAGED BY SYSTEM
	 USING ('/home/db2inst1/db2inst1/NODE0000/SP_MFTS1/FB_TS_TEMPUSR01')
	 EXTENTSIZE 32
	 PREFETCHSIZE 32
	 BUFFERPOOL FB_BP16K
	 NO FILE SYSTEM CACHING
	 DROPPED TABLE RECOVERY OFF;

select TBSPACE from syscat.tablespaces where TBSPACE like 'FB%';