----------------------------------
-- BCP v1.2.0 New Metadata      --
----------------------------------

-- New Columns

ALTER TABLE SPFB_BCP_USERS_MD ADD MAIN_USER SMALLINT;
ALTER TABLE SPFB_BCP_COMPANY_MD ADD MAIN_USER_CODE VARCHAR(8);
ALTER TABLE SPFB_BCP_PRODUCTS_MD ADD REM_WMQFTE_QM VARCHAR(48);
ALTER TABLE SPFB_BCP_PRODUCTS_MD ADD REM_WMQFTE_AGENT VARCHAR(24);

COMMIT;
